name: First test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  connection_test:
    runs-on: ubuntu-latest
    steps:
      - name: repo code download
        uses: actions/checkout@v4

      - name: Instalacja Terraforma
        uses: hashicorp/setup-terraform@v3

      - name: Inicjalizacja (terraform init)
        run: terraform init

      - name: Planowanie (terraform plan)
        run: terraform plan -out=tfplan

      - name: Wdrozenie (terraform apply)
        run: terraform apply -auto-approve tfplan